import type { Metadata } from "next";
import "./globals.css";
import { WalletProviders } from "./providers/wallets.providers";
import { ThemeProvider } from "./providers/theme.provider";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "TSender",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background">
        <ThemeProvider>
          <WalletProviders>
            <Header />
            {props.children}
          </WalletProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
